POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My First Blog Post",
    "author": "John Smith",
    "url": "https://example.com/blog/first-post",
    "likes": 0
}